### ISSUE TITLE
Links in readme are not working

### ISSUE THREAD

**Issue by Ishaan-11** [iona-b/iona-b.github.io#1]
opening any link in readme redirects to  `https://github.com/iona-b/iona-b.github.io/blob/iona/ionabrabender.com`
![image](https://user-images.githubusercontent.com/51826621/105632672-6b0d8000-5e7a-11eb-95b4-409b37bd070b.png)
i think it should be a complete url `https://ionabrabender.com` instead of `ionabrabender.com`

**Comment by iona-b** [comment]
Thanks, Ishaan! I hadn't noticed that.
